// <auto-generated />
using System;
using FIVESTARS.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FIVESTARS.Infra.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211011224855_aditional_reservation2")]
    partial class aditional_reservation2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("FIVESTARS.Domain.Entities.Bedroom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BED_TYPE")
                        .HasColumnType("longtext");

                    b.Property<int>("DOOR")
                        .HasColumnType("int");

                    b.Property<int>("FLOOR")
                        .HasColumnType("int");

                    b.Property<string>("MORE_INFORMATION")
                        .HasColumnType("longtext");

                    b.Property<int>("QUANTITY_BATHROOM")
                        .HasColumnType("int");

                    b.Property<int>("QUANTITY_BEDS")
                        .HasColumnType("int");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BEDROOM");
                });

            modelBuilder.Entity("FIVESTARS.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("BIRTH_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CEP")
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("EMAIL")
                        .HasColumnType("longtext");

                    b.Property<string>("NOME")
                        .HasColumnType("longtext");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CLIENT");
                });

            modelBuilder.Entity("FIVESTARS.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FINAL_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_BEDROOM")
                        .HasColumnType("int");

                    b.Property<int>("ID_CLIENT")
                        .HasColumnType("int");

                    b.Property<DateTime>("INITIAL_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OBSERVATION")
                        .HasColumnType("longtext");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_BEDROOM");

                    b.HasIndex("ID_CLIENT");

                    b.ToTable("RESERVATION");
                });

            modelBuilder.Entity("FIVESTARS.Domain.Entities.Teste", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("TABELA_TESTE");
                });

            modelBuilder.Entity("FIVESTARS.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("FIVESTARS.Domain.Entities.Bedroom", "BEDROOM")
                        .WithMany("RESERVATION")
                        .HasForeignKey("ID_BEDROOM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIVESTARS.Domain.Entities.Client", "CLIENT")
                        .WithMany("RESERVATION")
                        .HasForeignKey("ID_CLIENT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BEDROOM");

                    b.Navigation("CLIENT");
                });

            modelBuilder.Entity("FIVESTARS.Domain.Entities.Bedroom", b =>
                {
                    b.Navigation("RESERVATION");
                });

            modelBuilder.Entity("FIVESTARS.Domain.Entities.Client", b =>
                {
                    b.Navigation("RESERVATION");
                });
#pragma warning restore 612, 618
        }
    }
}
